kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test
  name: devops
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]  